/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my_youtube_automation;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws InterruptedException {
        System.out.println(new App().getGreeting());
        YoutubeAutomation youtubeAutomation = new YoutubeAutomation();
        YoutubeAutomation.createDriver();
    
         youtubeAutomation.start();
        youtubeAutomation.search("Selenium");
       youtubeAutomation.SearchAboutUs();

        youtubeAutomation.ViewMovieSelections();
        youtubeAutomation.endTest();
}
}
